services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db, redis]
    volumes: ["./:/app"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: hyperdrive
      POSTGRES_PASSWORD: hyperdrive
      POSTGRES_DB: hyperdrive
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

volumes:
  pgdata: